// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Book is the predicate function for book builders.
type Book func(*sql.Selector)

// Bookstatus is the predicate function for bookstatus builders.
type Bookstatus func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// RoomInfo is the predicate function for roominfo builders.
type RoomInfo func(*sql.Selector)

// RoomStatus is the predicate function for roomstatus builders.
type RoomStatus func(*sql.Selector)

// RoomType is the predicate function for roomtype builders.
type RoomType func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserStatus is the predicate function for userstatus builders.
type UserStatus func(*sql.Selector)
