// Code generated by entc, DO NOT EDIT.

package userstatus

const (
	// Label holds the string label denoting the userstatus type in the database.
	Label = "user_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSTATUS holds the string denoting the status field in the database.
	FieldSTATUS = "status"

	// EdgeUSERSTATUSUSER holds the string denoting the userstatus_user edge name in mutations.
	EdgeUSERSTATUSUSER = "USERSTATUS_USER"

	// Table holds the table name of the userstatus in the database.
	Table = "user_status"
	// USERSTATUSUSERTable is the table the holds the USERSTATUS_USER relation/edge.
	USERSTATUSUSERTable = "users"
	// USERSTATUSUSERInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	USERSTATUSUSERInverseTable = "users"
	// USERSTATUSUSERColumn is the table column denoting the USERSTATUS_USER relation/edge.
	USERSTATUSUSERColumn = "user_status_userstatus_user"
)

// Columns holds all SQL columns for userstatus fields.
var Columns = []string{
	FieldID,
	FieldSTATUS,
}

var (
	// STATUSValidator is a validator for the "STATUS" field. It is called by the builders before save.
	STATUSValidator func(string) error
)
