// Code generated by entc, DO NOT EDIT.

package userstatus

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/m16_z/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// STATUS applies equality check predicate on the "STATUS" field. It's identical to STATUSEQ.
func STATUS(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSTATUS), v))
	})
}

// STATUSEQ applies the EQ predicate on the "STATUS" field.
func STATUSEQ(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSTATUS), v))
	})
}

// STATUSNEQ applies the NEQ predicate on the "STATUS" field.
func STATUSNEQ(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSTATUS), v))
	})
}

// STATUSIn applies the In predicate on the "STATUS" field.
func STATUSIn(vs ...string) predicate.UserStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSTATUS), v...))
	})
}

// STATUSNotIn applies the NotIn predicate on the "STATUS" field.
func STATUSNotIn(vs ...string) predicate.UserStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.UserStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSTATUS), v...))
	})
}

// STATUSGT applies the GT predicate on the "STATUS" field.
func STATUSGT(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSTATUS), v))
	})
}

// STATUSGTE applies the GTE predicate on the "STATUS" field.
func STATUSGTE(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSTATUS), v))
	})
}

// STATUSLT applies the LT predicate on the "STATUS" field.
func STATUSLT(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSTATUS), v))
	})
}

// STATUSLTE applies the LTE predicate on the "STATUS" field.
func STATUSLTE(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSTATUS), v))
	})
}

// STATUSContains applies the Contains predicate on the "STATUS" field.
func STATUSContains(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSTATUS), v))
	})
}

// STATUSHasPrefix applies the HasPrefix predicate on the "STATUS" field.
func STATUSHasPrefix(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSTATUS), v))
	})
}

// STATUSHasSuffix applies the HasSuffix predicate on the "STATUS" field.
func STATUSHasSuffix(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSTATUS), v))
	})
}

// STATUSEqualFold applies the EqualFold predicate on the "STATUS" field.
func STATUSEqualFold(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSTATUS), v))
	})
}

// STATUSContainsFold applies the ContainsFold predicate on the "STATUS" field.
func STATUSContainsFold(v string) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSTATUS), v))
	})
}

// HasUSERSTATUSUSER applies the HasEdge predicate on the "USERSTATUS_USER" edge.
func HasUSERSTATUSUSER() predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(USERSTATUSUSERTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, USERSTATUSUSERTable, USERSTATUSUSERColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUSERSTATUSUSERWith applies the HasEdge predicate on the "USERSTATUS_USER" edge with a given conditions (other predicates).
func HasUSERSTATUSUSERWith(preds ...predicate.User) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(USERSTATUSUSERInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, USERSTATUSUSERTable, USERSTATUSUSERColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.UserStatus) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.UserStatus) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserStatus) predicate.UserStatus {
	return predicate.UserStatus(func(s *sql.Selector) {
		p(s.Not())
	})
}
