// Code generated by entc, DO NOT EDIT.

package roomtype

const (
	// Label holds the string label denoting the roomtype type in the database.
	Label = "room_type"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldROOMTYPEDATA holds the string denoting the roomtypedata field in the database.
	FieldROOMTYPEDATA = "roomtypedata"
	// FieldCOSTDATA holds the string denoting the costdata field in the database.
	FieldCOSTDATA = "costdata"

	// EdgeROOMTYPEROOM holds the string denoting the roomtype_room edge name in mutations.
	EdgeROOMTYPEROOM = "ROOMTYPE_ROOM"

	// Table holds the table name of the roomtype in the database.
	Table = "room_types"
	// ROOMTYPEROOMTable is the table the holds the ROOMTYPE_ROOM relation/edge.
	ROOMTYPEROOMTable = "rooms"
	// ROOMTYPEROOMInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	ROOMTYPEROOMInverseTable = "rooms"
	// ROOMTYPEROOMColumn is the table column denoting the ROOMTYPE_ROOM relation/edge.
	ROOMTYPEROOMColumn = "room_type_roomtype_room"
)

// Columns holds all SQL columns for roomtype fields.
var Columns = []string{
	FieldID,
	FieldROOMTYPEDATA,
	FieldCOSTDATA,
}

var (
	// ROOMTYPEDATAValidator is a validator for the "ROOMTYPEDATA" field. It is called by the builders before save.
	ROOMTYPEDATAValidator func(string) error
)
