// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/m16_z/app/ent/book"
	"github.com/m16_z/app/ent/bookstatus"
	"github.com/m16_z/app/ent/room"
	"github.com/m16_z/app/ent/user"
)

// Book is the model entity for the Book schema.
type Book struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// RESERVATIONS holds the value of the "RESERVATIONS" field.
	RESERVATIONS time.Time `json:"RESERVATIONS,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BookQuery when eager-loading is set.
	Edges                      BookEdges `json:"edges"`
	bookstatus_bookstatus_book *int
	room_room_book             *int
	user_user_book             *int
}

// BookEdges holds the relations/edges for other nodes in the graph.
type BookEdges struct {
	// BOOKUSER holds the value of the BOOK_USER edge.
	BOOKUSER *User
	// BOOKROOM holds the value of the BOOK_ROOM edge.
	BOOKROOM *Room
	// BOOKBOOKSTATUS holds the value of the BOOK_BOOKSTATUS edge.
	BOOKBOOKSTATUS *Bookstatus
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// BOOKUSEROrErr returns the BOOKUSER value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookEdges) BOOKUSEROrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.BOOKUSER == nil {
			// The edge BOOK_USER was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.BOOKUSER, nil
	}
	return nil, &NotLoadedError{edge: "BOOK_USER"}
}

// BOOKROOMOrErr returns the BOOKROOM value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookEdges) BOOKROOMOrErr() (*Room, error) {
	if e.loadedTypes[1] {
		if e.BOOKROOM == nil {
			// The edge BOOK_ROOM was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: room.Label}
		}
		return e.BOOKROOM, nil
	}
	return nil, &NotLoadedError{edge: "BOOK_ROOM"}
}

// BOOKBOOKSTATUSOrErr returns the BOOKBOOKSTATUS value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e BookEdges) BOOKBOOKSTATUSOrErr() (*Bookstatus, error) {
	if e.loadedTypes[2] {
		if e.BOOKBOOKSTATUS == nil {
			// The edge BOOK_BOOKSTATUS was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: bookstatus.Label}
		}
		return e.BOOKBOOKSTATUS, nil
	}
	return nil, &NotLoadedError{edge: "BOOK_BOOKSTATUS"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Book) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
		&sql.NullTime{},  // RESERVATIONS
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Book) fkValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // bookstatus_bookstatus_book
		&sql.NullInt64{}, // room_room_book
		&sql.NullInt64{}, // user_user_book
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Book fields.
func (b *Book) assignValues(values ...interface{}) error {
	if m, n := len(values), len(book.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	b.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field RESERVATIONS", values[0])
	} else if value.Valid {
		b.RESERVATIONS = value.Time
	}
	values = values[1:]
	if len(values) == len(book.ForeignKeys) {
		if value, ok := values[0].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field bookstatus_bookstatus_book", value)
		} else if value.Valid {
			b.bookstatus_bookstatus_book = new(int)
			*b.bookstatus_bookstatus_book = int(value.Int64)
		}
		if value, ok := values[1].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field room_room_book", value)
		} else if value.Valid {
			b.room_room_book = new(int)
			*b.room_room_book = int(value.Int64)
		}
		if value, ok := values[2].(*sql.NullInt64); !ok {
			return fmt.Errorf("unexpected type %T for edge-field user_user_book", value)
		} else if value.Valid {
			b.user_user_book = new(int)
			*b.user_user_book = int(value.Int64)
		}
	}
	return nil
}

// QueryBOOKUSER queries the BOOK_USER edge of the Book.
func (b *Book) QueryBOOKUSER() *UserQuery {
	return (&BookClient{config: b.config}).QueryBOOKUSER(b)
}

// QueryBOOKROOM queries the BOOK_ROOM edge of the Book.
func (b *Book) QueryBOOKROOM() *RoomQuery {
	return (&BookClient{config: b.config}).QueryBOOKROOM(b)
}

// QueryBOOKBOOKSTATUS queries the BOOK_BOOKSTATUS edge of the Book.
func (b *Book) QueryBOOKBOOKSTATUS() *BookstatusQuery {
	return (&BookClient{config: b.config}).QueryBOOKBOOKSTATUS(b)
}

// Update returns a builder for updating this Book.
// Note that, you need to call Book.Unwrap() before calling this method, if this Book
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Book) Update() *BookUpdateOne {
	return (&BookClient{config: b.config}).UpdateOne(b)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (b *Book) Unwrap() *Book {
	tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("ent: Book is not a transactional entity")
	}
	b.config.driver = tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Book) String() string {
	var builder strings.Builder
	builder.WriteString("Book(")
	builder.WriteString(fmt.Sprintf("id=%v", b.ID))
	builder.WriteString(", RESERVATIONS=")
	builder.WriteString(b.RESERVATIONS.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Books is a parsable slice of Book.
type Books []*Book

func (b Books) config(cfg config) {
	for _i := range b {
		b[_i].config = cfg
	}
}
