// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/m16_z/app/ent/predicate"
	"github.com/m16_z/app/ent/room"
	"github.com/m16_z/app/ent/roominfo"
)

// RoomInfoUpdate is the builder for updating RoomInfo entities.
type RoomInfoUpdate struct {
	config
	hooks      []Hook
	mutation   *RoomInfoMutation
	predicates []predicate.RoomInfo
}

// Where adds a new predicate for the builder.
func (riu *RoomInfoUpdate) Where(ps ...predicate.RoomInfo) *RoomInfoUpdate {
	riu.predicates = append(riu.predicates, ps...)
	return riu
}

// SetINFOBED sets the INFOBED field.
func (riu *RoomInfoUpdate) SetINFOBED(i int) *RoomInfoUpdate {
	riu.mutation.ResetINFOBED()
	riu.mutation.SetINFOBED(i)
	return riu
}

// AddINFOBED adds i to INFOBED.
func (riu *RoomInfoUpdate) AddINFOBED(i int) *RoomInfoUpdate {
	riu.mutation.AddINFOBED(i)
	return riu
}

// SetINFOREFRIGERAT sets the INFOREFRIGERAT field.
func (riu *RoomInfoUpdate) SetINFOREFRIGERAT(i int) *RoomInfoUpdate {
	riu.mutation.ResetINFOREFRIGERAT()
	riu.mutation.SetINFOREFRIGERAT(i)
	return riu
}

// AddINFOREFRIGERAT adds i to INFOREFRIGERAT.
func (riu *RoomInfoUpdate) AddINFOREFRIGERAT(i int) *RoomInfoUpdate {
	riu.mutation.AddINFOREFRIGERAT(i)
	return riu
}

// SetINFOWARDROB sets the INFOWARDROB field.
func (riu *RoomInfoUpdate) SetINFOWARDROB(i int) *RoomInfoUpdate {
	riu.mutation.ResetINFOWARDROB()
	riu.mutation.SetINFOWARDROB(i)
	return riu
}

// AddINFOWARDROB adds i to INFOWARDROB.
func (riu *RoomInfoUpdate) AddINFOWARDROB(i int) *RoomInfoUpdate {
	riu.mutation.AddINFOWARDROB(i)
	return riu
}

// SetINFOOFFICEDE sets the INFOOFFICEDE field.
func (riu *RoomInfoUpdate) SetINFOOFFICEDE(i int) *RoomInfoUpdate {
	riu.mutation.ResetINFOOFFICEDE()
	riu.mutation.SetINFOOFFICEDE(i)
	return riu
}

// AddINFOOFFICEDE adds i to INFOOFFICEDE.
func (riu *RoomInfoUpdate) AddINFOOFFICEDE(i int) *RoomInfoUpdate {
	riu.mutation.AddINFOOFFICEDE(i)
	return riu
}

// AddINFOROOMIDs adds the INFO_ROOM edge to Room by ids.
func (riu *RoomInfoUpdate) AddINFOROOMIDs(ids ...int) *RoomInfoUpdate {
	riu.mutation.AddINFOROOMIDs(ids...)
	return riu
}

// AddINFOROOM adds the INFO_ROOM edges to Room.
func (riu *RoomInfoUpdate) AddINFOROOM(r ...*Room) *RoomInfoUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return riu.AddINFOROOMIDs(ids...)
}

// Mutation returns the RoomInfoMutation object of the builder.
func (riu *RoomInfoUpdate) Mutation() *RoomInfoMutation {
	return riu.mutation
}

// RemoveINFOROOMIDs removes the INFO_ROOM edge to Room by ids.
func (riu *RoomInfoUpdate) RemoveINFOROOMIDs(ids ...int) *RoomInfoUpdate {
	riu.mutation.RemoveINFOROOMIDs(ids...)
	return riu
}

// RemoveINFOROOM removes INFO_ROOM edges to Room.
func (riu *RoomInfoUpdate) RemoveINFOROOM(r ...*Room) *RoomInfoUpdate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return riu.RemoveINFOROOMIDs(ids...)
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (riu *RoomInfoUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(riu.hooks) == 0 {
		affected, err = riu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			riu.mutation = mutation
			affected, err = riu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(riu.hooks) - 1; i >= 0; i-- {
			mut = riu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, riu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (riu *RoomInfoUpdate) SaveX(ctx context.Context) int {
	affected, err := riu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (riu *RoomInfoUpdate) Exec(ctx context.Context) error {
	_, err := riu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (riu *RoomInfoUpdate) ExecX(ctx context.Context) {
	if err := riu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (riu *RoomInfoUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roominfo.Table,
			Columns: roominfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roominfo.FieldID,
			},
		},
	}
	if ps := riu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := riu.mutation.INFOBED(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOBED,
		})
	}
	if value, ok := riu.mutation.AddedINFOBED(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOBED,
		})
	}
	if value, ok := riu.mutation.INFOREFRIGERAT(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOREFRIGERAT,
		})
	}
	if value, ok := riu.mutation.AddedINFOREFRIGERAT(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOREFRIGERAT,
		})
	}
	if value, ok := riu.mutation.INFOWARDROB(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOWARDROB,
		})
	}
	if value, ok := riu.mutation.AddedINFOWARDROB(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOWARDROB,
		})
	}
	if value, ok := riu.mutation.INFOOFFICEDE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOOFFICEDE,
		})
	}
	if value, ok := riu.mutation.AddedINFOOFFICEDE(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOOFFICEDE,
		})
	}
	if nodes := riu.mutation.RemovedINFOROOMIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roominfo.INFOROOMTable,
			Columns: []string{roominfo.INFOROOMColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riu.mutation.INFOROOMIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roominfo.INFOROOMTable,
			Columns: []string{roominfo.INFOROOMColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, riu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roominfo.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// RoomInfoUpdateOne is the builder for updating a single RoomInfo entity.
type RoomInfoUpdateOne struct {
	config
	hooks    []Hook
	mutation *RoomInfoMutation
}

// SetINFOBED sets the INFOBED field.
func (riuo *RoomInfoUpdateOne) SetINFOBED(i int) *RoomInfoUpdateOne {
	riuo.mutation.ResetINFOBED()
	riuo.mutation.SetINFOBED(i)
	return riuo
}

// AddINFOBED adds i to INFOBED.
func (riuo *RoomInfoUpdateOne) AddINFOBED(i int) *RoomInfoUpdateOne {
	riuo.mutation.AddINFOBED(i)
	return riuo
}

// SetINFOREFRIGERAT sets the INFOREFRIGERAT field.
func (riuo *RoomInfoUpdateOne) SetINFOREFRIGERAT(i int) *RoomInfoUpdateOne {
	riuo.mutation.ResetINFOREFRIGERAT()
	riuo.mutation.SetINFOREFRIGERAT(i)
	return riuo
}

// AddINFOREFRIGERAT adds i to INFOREFRIGERAT.
func (riuo *RoomInfoUpdateOne) AddINFOREFRIGERAT(i int) *RoomInfoUpdateOne {
	riuo.mutation.AddINFOREFRIGERAT(i)
	return riuo
}

// SetINFOWARDROB sets the INFOWARDROB field.
func (riuo *RoomInfoUpdateOne) SetINFOWARDROB(i int) *RoomInfoUpdateOne {
	riuo.mutation.ResetINFOWARDROB()
	riuo.mutation.SetINFOWARDROB(i)
	return riuo
}

// AddINFOWARDROB adds i to INFOWARDROB.
func (riuo *RoomInfoUpdateOne) AddINFOWARDROB(i int) *RoomInfoUpdateOne {
	riuo.mutation.AddINFOWARDROB(i)
	return riuo
}

// SetINFOOFFICEDE sets the INFOOFFICEDE field.
func (riuo *RoomInfoUpdateOne) SetINFOOFFICEDE(i int) *RoomInfoUpdateOne {
	riuo.mutation.ResetINFOOFFICEDE()
	riuo.mutation.SetINFOOFFICEDE(i)
	return riuo
}

// AddINFOOFFICEDE adds i to INFOOFFICEDE.
func (riuo *RoomInfoUpdateOne) AddINFOOFFICEDE(i int) *RoomInfoUpdateOne {
	riuo.mutation.AddINFOOFFICEDE(i)
	return riuo
}

// AddINFOROOMIDs adds the INFO_ROOM edge to Room by ids.
func (riuo *RoomInfoUpdateOne) AddINFOROOMIDs(ids ...int) *RoomInfoUpdateOne {
	riuo.mutation.AddINFOROOMIDs(ids...)
	return riuo
}

// AddINFOROOM adds the INFO_ROOM edges to Room.
func (riuo *RoomInfoUpdateOne) AddINFOROOM(r ...*Room) *RoomInfoUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return riuo.AddINFOROOMIDs(ids...)
}

// Mutation returns the RoomInfoMutation object of the builder.
func (riuo *RoomInfoUpdateOne) Mutation() *RoomInfoMutation {
	return riuo.mutation
}

// RemoveINFOROOMIDs removes the INFO_ROOM edge to Room by ids.
func (riuo *RoomInfoUpdateOne) RemoveINFOROOMIDs(ids ...int) *RoomInfoUpdateOne {
	riuo.mutation.RemoveINFOROOMIDs(ids...)
	return riuo
}

// RemoveINFOROOM removes INFO_ROOM edges to Room.
func (riuo *RoomInfoUpdateOne) RemoveINFOROOM(r ...*Room) *RoomInfoUpdateOne {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return riuo.RemoveINFOROOMIDs(ids...)
}

// Save executes the query and returns the updated entity.
func (riuo *RoomInfoUpdateOne) Save(ctx context.Context) (*RoomInfo, error) {

	var (
		err  error
		node *RoomInfo
	)
	if len(riuo.hooks) == 0 {
		node, err = riuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomInfoMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			riuo.mutation = mutation
			node, err = riuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(riuo.hooks) - 1; i >= 0; i-- {
			mut = riuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, riuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (riuo *RoomInfoUpdateOne) SaveX(ctx context.Context) *RoomInfo {
	ri, err := riuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return ri
}

// Exec executes the query on the entity.
func (riuo *RoomInfoUpdateOne) Exec(ctx context.Context) error {
	_, err := riuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (riuo *RoomInfoUpdateOne) ExecX(ctx context.Context) {
	if err := riuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (riuo *RoomInfoUpdateOne) sqlSave(ctx context.Context) (ri *RoomInfo, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   roominfo.Table,
			Columns: roominfo.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roominfo.FieldID,
			},
		},
	}
	id, ok := riuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing RoomInfo.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := riuo.mutation.INFOBED(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOBED,
		})
	}
	if value, ok := riuo.mutation.AddedINFOBED(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOBED,
		})
	}
	if value, ok := riuo.mutation.INFOREFRIGERAT(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOREFRIGERAT,
		})
	}
	if value, ok := riuo.mutation.AddedINFOREFRIGERAT(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOREFRIGERAT,
		})
	}
	if value, ok := riuo.mutation.INFOWARDROB(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOWARDROB,
		})
	}
	if value, ok := riuo.mutation.AddedINFOWARDROB(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOWARDROB,
		})
	}
	if value, ok := riuo.mutation.INFOOFFICEDE(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOOFFICEDE,
		})
	}
	if value, ok := riuo.mutation.AddedINFOOFFICEDE(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roominfo.FieldINFOOFFICEDE,
		})
	}
	if nodes := riuo.mutation.RemovedINFOROOMIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roominfo.INFOROOMTable,
			Columns: []string{roominfo.INFOROOMColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := riuo.mutation.INFOROOMIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roominfo.INFOROOMTable,
			Columns: []string{roominfo.INFOROOMColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	ri = &RoomInfo{config: riuo.config}
	_spec.Assign = ri.assignValues
	_spec.ScanValues = ri.scanValues()
	if err = sqlgraph.UpdateNode(ctx, riuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roominfo.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return ri, nil
}
