// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/m16_z/app/ent/room"
	"github.com/m16_z/app/ent/roomtype"
)

// RoomTypeCreate is the builder for creating a RoomType entity.
type RoomTypeCreate struct {
	config
	mutation *RoomTypeMutation
	hooks    []Hook
}

// SetROOMTYPEDATA sets the ROOMTYPEDATA field.
func (rtc *RoomTypeCreate) SetROOMTYPEDATA(s string) *RoomTypeCreate {
	rtc.mutation.SetROOMTYPEDATA(s)
	return rtc
}

// SetCOSTDATA sets the COSTDATA field.
func (rtc *RoomTypeCreate) SetCOSTDATA(i int) *RoomTypeCreate {
	rtc.mutation.SetCOSTDATA(i)
	return rtc
}

// AddROOMTYPEROOMIDs adds the ROOMTYPE_ROOM edge to Room by ids.
func (rtc *RoomTypeCreate) AddROOMTYPEROOMIDs(ids ...int) *RoomTypeCreate {
	rtc.mutation.AddROOMTYPEROOMIDs(ids...)
	return rtc
}

// AddROOMTYPEROOM adds the ROOMTYPE_ROOM edges to Room.
func (rtc *RoomTypeCreate) AddROOMTYPEROOM(r ...*Room) *RoomTypeCreate {
	ids := make([]int, len(r))
	for i := range r {
		ids[i] = r[i].ID
	}
	return rtc.AddROOMTYPEROOMIDs(ids...)
}

// Mutation returns the RoomTypeMutation object of the builder.
func (rtc *RoomTypeCreate) Mutation() *RoomTypeMutation {
	return rtc.mutation
}

// Save creates the RoomType in the database.
func (rtc *RoomTypeCreate) Save(ctx context.Context) (*RoomType, error) {
	if _, ok := rtc.mutation.ROOMTYPEDATA(); !ok {
		return nil, &ValidationError{Name: "ROOMTYPEDATA", err: errors.New("ent: missing required field \"ROOMTYPEDATA\"")}
	}
	if v, ok := rtc.mutation.ROOMTYPEDATA(); ok {
		if err := roomtype.ROOMTYPEDATAValidator(v); err != nil {
			return nil, &ValidationError{Name: "ROOMTYPEDATA", err: fmt.Errorf("ent: validator failed for field \"ROOMTYPEDATA\": %w", err)}
		}
	}
	if _, ok := rtc.mutation.COSTDATA(); !ok {
		return nil, &ValidationError{Name: "COSTDATA", err: errors.New("ent: missing required field \"COSTDATA\"")}
	}
	var (
		err  error
		node *RoomType
	)
	if len(rtc.hooks) == 0 {
		node, err = rtc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*RoomTypeMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			rtc.mutation = mutation
			node, err = rtc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(rtc.hooks) - 1; i >= 0; i-- {
			mut = rtc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, rtc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (rtc *RoomTypeCreate) SaveX(ctx context.Context) *RoomType {
	v, err := rtc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (rtc *RoomTypeCreate) sqlSave(ctx context.Context) (*RoomType, error) {
	rt, _spec := rtc.createSpec()
	if err := sqlgraph.CreateNode(ctx, rtc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	rt.ID = int(id)
	return rt, nil
}

func (rtc *RoomTypeCreate) createSpec() (*RoomType, *sqlgraph.CreateSpec) {
	var (
		rt    = &RoomType{config: rtc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: roomtype.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: roomtype.FieldID,
			},
		}
	)
	if value, ok := rtc.mutation.ROOMTYPEDATA(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: roomtype.FieldROOMTYPEDATA,
		})
		rt.ROOMTYPEDATA = value
	}
	if value, ok := rtc.mutation.COSTDATA(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: roomtype.FieldCOSTDATA,
		})
		rt.COSTDATA = value
	}
	if nodes := rtc.mutation.ROOMTYPEROOMIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roomtype.ROOMTYPEROOMTable,
			Columns: []string{roomtype.ROOMTYPEROOMColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: room.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return rt, _spec
}
