// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/m16_z/app/ent/book"
	"github.com/m16_z/app/ent/user"
	"github.com/m16_z/app/ent/userstatus"
)

// UserCreate is the builder for creating a User entity.
type UserCreate struct {
	config
	mutation *UserMutation
	hooks    []Hook
}

// SetUSEREMAIL sets the USEREMAIL field.
func (uc *UserCreate) SetUSEREMAIL(s string) *UserCreate {
	uc.mutation.SetUSEREMAIL(s)
	return uc
}

// SetUSERNAME sets the USERNAME field.
func (uc *UserCreate) SetUSERNAME(s string) *UserCreate {
	uc.mutation.SetUSERNAME(s)
	return uc
}

// AddUSERBOOKIDs adds the USER_BOOK edge to Book by ids.
func (uc *UserCreate) AddUSERBOOKIDs(ids ...int) *UserCreate {
	uc.mutation.AddUSERBOOKIDs(ids...)
	return uc
}

// AddUSERBOOK adds the USER_BOOK edges to Book.
func (uc *UserCreate) AddUSERBOOK(b ...*Book) *UserCreate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uc.AddUSERBOOKIDs(ids...)
}

// SetUSERUSERSTATUSID sets the USER_USERSTATUS edge to UserStatus by id.
func (uc *UserCreate) SetUSERUSERSTATUSID(id int) *UserCreate {
	uc.mutation.SetUSERUSERSTATUSID(id)
	return uc
}

// SetNillableUSERUSERSTATUSID sets the USER_USERSTATUS edge to UserStatus by id if the given value is not nil.
func (uc *UserCreate) SetNillableUSERUSERSTATUSID(id *int) *UserCreate {
	if id != nil {
		uc = uc.SetUSERUSERSTATUSID(*id)
	}
	return uc
}

// SetUSERUSERSTATUS sets the USER_USERSTATUS edge to UserStatus.
func (uc *UserCreate) SetUSERUSERSTATUS(u *UserStatus) *UserCreate {
	return uc.SetUSERUSERSTATUSID(u.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uc *UserCreate) Mutation() *UserMutation {
	return uc.mutation
}

// Save creates the User in the database.
func (uc *UserCreate) Save(ctx context.Context) (*User, error) {
	if _, ok := uc.mutation.USEREMAIL(); !ok {
		return nil, &ValidationError{Name: "USEREMAIL", err: errors.New("ent: missing required field \"USEREMAIL\"")}
	}
	if v, ok := uc.mutation.USEREMAIL(); ok {
		if err := user.USEREMAILValidator(v); err != nil {
			return nil, &ValidationError{Name: "USEREMAIL", err: fmt.Errorf("ent: validator failed for field \"USEREMAIL\": %w", err)}
		}
	}
	if _, ok := uc.mutation.USERNAME(); !ok {
		return nil, &ValidationError{Name: "USERNAME", err: errors.New("ent: missing required field \"USERNAME\"")}
	}
	if v, ok := uc.mutation.USERNAME(); ok {
		if err := user.USERNAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "USERNAME", err: fmt.Errorf("ent: validator failed for field \"USERNAME\": %w", err)}
		}
	}
	var (
		err  error
		node *User
	)
	if len(uc.hooks) == 0 {
		node, err = uc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uc.mutation = mutation
			node, err = uc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uc.hooks) - 1; i >= 0; i-- {
			mut = uc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (uc *UserCreate) SaveX(ctx context.Context) *User {
	v, err := uc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (uc *UserCreate) sqlSave(ctx context.Context) (*User, error) {
	u, _spec := uc.createSpec()
	if err := sqlgraph.CreateNode(ctx, uc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	u.ID = int(id)
	return u, nil
}

func (uc *UserCreate) createSpec() (*User, *sqlgraph.CreateSpec) {
	var (
		u     = &User{config: uc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: user.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		}
	)
	if value, ok := uc.mutation.USEREMAIL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSEREMAIL,
		})
		u.USEREMAIL = value
	}
	if value, ok := uc.mutation.USERNAME(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSERNAME,
		})
		u.USERNAME = value
	}
	if nodes := uc.mutation.USERBOOKIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.USERBOOKTable,
			Columns: []string{user.USERBOOKColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: book.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := uc.mutation.USERUSERSTATUSIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.USERUSERSTATUSTable,
			Columns: []string{user.USERUSERSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: userstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return u, _spec
}
