// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/m16_z/app/ent/book"
	"github.com/m16_z/app/ent/predicate"
	"github.com/m16_z/app/ent/user"
	"github.com/m16_z/app/ent/userstatus"
)

// UserUpdate is the builder for updating User entities.
type UserUpdate struct {
	config
	hooks      []Hook
	mutation   *UserMutation
	predicates []predicate.User
}

// Where adds a new predicate for the builder.
func (uu *UserUpdate) Where(ps ...predicate.User) *UserUpdate {
	uu.predicates = append(uu.predicates, ps...)
	return uu
}

// SetUSEREMAIL sets the USEREMAIL field.
func (uu *UserUpdate) SetUSEREMAIL(s string) *UserUpdate {
	uu.mutation.SetUSEREMAIL(s)
	return uu
}

// SetUSERNAME sets the USERNAME field.
func (uu *UserUpdate) SetUSERNAME(s string) *UserUpdate {
	uu.mutation.SetUSERNAME(s)
	return uu
}

// AddUSERBOOKIDs adds the USER_BOOK edge to Book by ids.
func (uu *UserUpdate) AddUSERBOOKIDs(ids ...int) *UserUpdate {
	uu.mutation.AddUSERBOOKIDs(ids...)
	return uu
}

// AddUSERBOOK adds the USER_BOOK edges to Book.
func (uu *UserUpdate) AddUSERBOOK(b ...*Book) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.AddUSERBOOKIDs(ids...)
}

// SetUSERUSERSTATUSID sets the USER_USERSTATUS edge to UserStatus by id.
func (uu *UserUpdate) SetUSERUSERSTATUSID(id int) *UserUpdate {
	uu.mutation.SetUSERUSERSTATUSID(id)
	return uu
}

// SetNillableUSERUSERSTATUSID sets the USER_USERSTATUS edge to UserStatus by id if the given value is not nil.
func (uu *UserUpdate) SetNillableUSERUSERSTATUSID(id *int) *UserUpdate {
	if id != nil {
		uu = uu.SetUSERUSERSTATUSID(*id)
	}
	return uu
}

// SetUSERUSERSTATUS sets the USER_USERSTATUS edge to UserStatus.
func (uu *UserUpdate) SetUSERUSERSTATUS(u *UserStatus) *UserUpdate {
	return uu.SetUSERUSERSTATUSID(u.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uu *UserUpdate) Mutation() *UserMutation {
	return uu.mutation
}

// RemoveUSERBOOKIDs removes the USER_BOOK edge to Book by ids.
func (uu *UserUpdate) RemoveUSERBOOKIDs(ids ...int) *UserUpdate {
	uu.mutation.RemoveUSERBOOKIDs(ids...)
	return uu
}

// RemoveUSERBOOK removes USER_BOOK edges to Book.
func (uu *UserUpdate) RemoveUSERBOOK(b ...*Book) *UserUpdate {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uu.RemoveUSERBOOKIDs(ids...)
}

// ClearUSERUSERSTATUS clears the USER_USERSTATUS edge to UserStatus.
func (uu *UserUpdate) ClearUSERUSERSTATUS() *UserUpdate {
	uu.mutation.ClearUSERUSERSTATUS()
	return uu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (uu *UserUpdate) Save(ctx context.Context) (int, error) {
	if v, ok := uu.mutation.USEREMAIL(); ok {
		if err := user.USEREMAILValidator(v); err != nil {
			return 0, &ValidationError{Name: "USEREMAIL", err: fmt.Errorf("ent: validator failed for field \"USEREMAIL\": %w", err)}
		}
	}
	if v, ok := uu.mutation.USERNAME(); ok {
		if err := user.USERNAMEValidator(v); err != nil {
			return 0, &ValidationError{Name: "USERNAME", err: fmt.Errorf("ent: validator failed for field \"USERNAME\": %w", err)}
		}
	}

	var (
		err      error
		affected int
	)
	if len(uu.hooks) == 0 {
		affected, err = uu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uu.mutation = mutation
			affected, err = uu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(uu.hooks) - 1; i >= 0; i-- {
			mut = uu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (uu *UserUpdate) SaveX(ctx context.Context) int {
	affected, err := uu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uu *UserUpdate) Exec(ctx context.Context) error {
	_, err := uu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uu *UserUpdate) ExecX(ctx context.Context) {
	if err := uu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uu *UserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		},
	}
	if ps := uu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uu.mutation.USEREMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSEREMAIL,
		})
	}
	if value, ok := uu.mutation.USERNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSERNAME,
		})
	}
	if nodes := uu.mutation.RemovedUSERBOOKIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.USERBOOKTable,
			Columns: []string{user.USERBOOKColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: book.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.USERBOOKIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.USERBOOKTable,
			Columns: []string{user.USERBOOKColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: book.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uu.mutation.USERUSERSTATUSCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.USERUSERSTATUSTable,
			Columns: []string{user.USERUSERSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: userstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uu.mutation.USERUSERSTATUSIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.USERUSERSTATUSTable,
			Columns: []string{user.USERUSERSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: userstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, uu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// UserUpdateOne is the builder for updating a single User entity.
type UserUpdateOne struct {
	config
	hooks    []Hook
	mutation *UserMutation
}

// SetUSEREMAIL sets the USEREMAIL field.
func (uuo *UserUpdateOne) SetUSEREMAIL(s string) *UserUpdateOne {
	uuo.mutation.SetUSEREMAIL(s)
	return uuo
}

// SetUSERNAME sets the USERNAME field.
func (uuo *UserUpdateOne) SetUSERNAME(s string) *UserUpdateOne {
	uuo.mutation.SetUSERNAME(s)
	return uuo
}

// AddUSERBOOKIDs adds the USER_BOOK edge to Book by ids.
func (uuo *UserUpdateOne) AddUSERBOOKIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.AddUSERBOOKIDs(ids...)
	return uuo
}

// AddUSERBOOK adds the USER_BOOK edges to Book.
func (uuo *UserUpdateOne) AddUSERBOOK(b ...*Book) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.AddUSERBOOKIDs(ids...)
}

// SetUSERUSERSTATUSID sets the USER_USERSTATUS edge to UserStatus by id.
func (uuo *UserUpdateOne) SetUSERUSERSTATUSID(id int) *UserUpdateOne {
	uuo.mutation.SetUSERUSERSTATUSID(id)
	return uuo
}

// SetNillableUSERUSERSTATUSID sets the USER_USERSTATUS edge to UserStatus by id if the given value is not nil.
func (uuo *UserUpdateOne) SetNillableUSERUSERSTATUSID(id *int) *UserUpdateOne {
	if id != nil {
		uuo = uuo.SetUSERUSERSTATUSID(*id)
	}
	return uuo
}

// SetUSERUSERSTATUS sets the USER_USERSTATUS edge to UserStatus.
func (uuo *UserUpdateOne) SetUSERUSERSTATUS(u *UserStatus) *UserUpdateOne {
	return uuo.SetUSERUSERSTATUSID(u.ID)
}

// Mutation returns the UserMutation object of the builder.
func (uuo *UserUpdateOne) Mutation() *UserMutation {
	return uuo.mutation
}

// RemoveUSERBOOKIDs removes the USER_BOOK edge to Book by ids.
func (uuo *UserUpdateOne) RemoveUSERBOOKIDs(ids ...int) *UserUpdateOne {
	uuo.mutation.RemoveUSERBOOKIDs(ids...)
	return uuo
}

// RemoveUSERBOOK removes USER_BOOK edges to Book.
func (uuo *UserUpdateOne) RemoveUSERBOOK(b ...*Book) *UserUpdateOne {
	ids := make([]int, len(b))
	for i := range b {
		ids[i] = b[i].ID
	}
	return uuo.RemoveUSERBOOKIDs(ids...)
}

// ClearUSERUSERSTATUS clears the USER_USERSTATUS edge to UserStatus.
func (uuo *UserUpdateOne) ClearUSERUSERSTATUS() *UserUpdateOne {
	uuo.mutation.ClearUSERUSERSTATUS()
	return uuo
}

// Save executes the query and returns the updated entity.
func (uuo *UserUpdateOne) Save(ctx context.Context) (*User, error) {
	if v, ok := uuo.mutation.USEREMAIL(); ok {
		if err := user.USEREMAILValidator(v); err != nil {
			return nil, &ValidationError{Name: "USEREMAIL", err: fmt.Errorf("ent: validator failed for field \"USEREMAIL\": %w", err)}
		}
	}
	if v, ok := uuo.mutation.USERNAME(); ok {
		if err := user.USERNAMEValidator(v); err != nil {
			return nil, &ValidationError{Name: "USERNAME", err: fmt.Errorf("ent: validator failed for field \"USERNAME\": %w", err)}
		}
	}

	var (
		err  error
		node *User
	)
	if len(uuo.hooks) == 0 {
		node, err = uuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*UserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			uuo.mutation = mutation
			node, err = uuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(uuo.hooks) - 1; i >= 0; i-- {
			mut = uuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, uuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (uuo *UserUpdateOne) SaveX(ctx context.Context) *User {
	u, err := uuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return u
}

// Exec executes the query on the entity.
func (uuo *UserUpdateOne) Exec(ctx context.Context) error {
	_, err := uuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uuo *UserUpdateOne) ExecX(ctx context.Context) {
	if err := uuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (uuo *UserUpdateOne) sqlSave(ctx context.Context) (u *User, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   user.Table,
			Columns: user.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: user.FieldID,
			},
		},
	}
	id, ok := uuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing User.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := uuo.mutation.USEREMAIL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSEREMAIL,
		})
	}
	if value, ok := uuo.mutation.USERNAME(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: user.FieldUSERNAME,
		})
	}
	if nodes := uuo.mutation.RemovedUSERBOOKIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.USERBOOKTable,
			Columns: []string{user.USERBOOKColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: book.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.USERBOOKIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   user.USERBOOKTable,
			Columns: []string{user.USERBOOKColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: book.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uuo.mutation.USERUSERSTATUSCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.USERUSERSTATUSTable,
			Columns: []string{user.USERUSERSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: userstatus.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uuo.mutation.USERUSERSTATUSIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   user.USERUSERSTATUSTable,
			Columns: []string{user.USERUSERSTATUSColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: userstatus.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	u = &User{config: uuo.config}
	_spec.Assign = u.assignValues
	_spec.ScanValues = u.scanValues()
	if err = sqlgraph.UpdateNode(ctx, uuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{user.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return u, nil
}
