/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersBook
 */
export interface ControllersBook {
    /**
     * 
     * @type {number}
     * @memberof ControllersBook
     */
    bookStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof ControllersBook
     */
    reservations?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBook
     */
    room?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBook
     */
    user?: number;
}

export function ControllersBookFromJSON(json: any): ControllersBook {
    return ControllersBookFromJSONTyped(json, false);
}

export function ControllersBookFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersBook {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookStatus': !exists(json, 'bookStatus') ? undefined : json['bookStatus'],
        'reservations': !exists(json, 'reservations') ? undefined : json['reservations'],
        'room': !exists(json, 'room') ? undefined : json['room'],
        'user': !exists(json, 'user') ? undefined : json['user'],
    };
}

export function ControllersBookToJSON(value?: ControllersBook | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookStatus': value.bookStatus,
        'reservations': value.reservations,
        'room': value.room,
        'user': value.user,
    };
}


