/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBookEdges,
    EntBookEdgesFromJSON,
    EntBookEdgesFromJSONTyped,
    EntBookEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBook
 */
export interface EntBook {
    /**
     * RESERVATIONS holds the value of the "RESERVATIONS" field.
     * @type {string}
     * @memberof EntBook
     */
    rESERVATIONS?: string;
    /**
     * 
     * @type {EntBookEdges}
     * @memberof EntBook
     */
    edges?: EntBookEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntBook
     */
    id?: number;
}

export function EntBookFromJSON(json: any): EntBook {
    return EntBookFromJSONTyped(json, false);
}

export function EntBookFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBook {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'rESERVATIONS': !exists(json, 'RESERVATIONS') ? undefined : json['RESERVATIONS'],
        'edges': !exists(json, 'edges') ? undefined : EntBookEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntBookToJSON(value?: EntBook | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'RESERVATIONS': value.rESERVATIONS,
        'edges': EntBookEdgesToJSON(value.edges),
        'id': value.id,
    };
}


