/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBookstatus,
    EntBookstatusFromJSON,
    EntBookstatusFromJSONTyped,
    EntBookstatusToJSON,
    EntRoom,
    EntRoomFromJSON,
    EntRoomFromJSONTyped,
    EntRoomToJSON,
    EntUser,
    EntUserFromJSON,
    EntUserFromJSONTyped,
    EntUserToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntBookEdges
 */
export interface EntBookEdges {
    /**
     * 
     * @type {EntBookstatus}
     * @memberof EntBookEdges
     */
    bookbookstatus?: EntBookstatus;
    /**
     * 
     * @type {EntRoom}
     * @memberof EntBookEdges
     */
    bookroom?: EntRoom;
    /**
     * 
     * @type {EntUser}
     * @memberof EntBookEdges
     */
    bookuser?: EntUser;
}

export function EntBookEdgesFromJSON(json: any): EntBookEdges {
    return EntBookEdgesFromJSONTyped(json, false);
}

export function EntBookEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntBookEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'bookbookstatus': !exists(json, 'BOOKBOOKSTATUS') ? undefined : EntBookstatusFromJSON(json['BOOKBOOKSTATUS']),
        'bookroom': !exists(json, 'BOOKROOM') ? undefined : EntRoomFromJSON(json['BOOKROOM']),
        'bookuser': !exists(json, 'BOOKUSER') ? undefined : EntUserFromJSON(json['BOOKUSER']),
    };
}

export function EntBookEdgesToJSON(value?: EntBookEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'bookbookstatus': EntBookstatusToJSON(value.bookbookstatus),
        'bookroom': EntRoomToJSON(value.bookroom),
        'bookuser': EntUserToJSON(value.bookuser),
    };
}


