/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntRoomTypeEdges,
    EntRoomTypeEdgesFromJSON,
    EntRoomTypeEdgesFromJSONTyped,
    EntRoomTypeEdgesToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomType
 */
export interface EntRoomType {
    /**
     * COSTDATA holds the value of the "COSTDATA" field.
     * @type {number}
     * @memberof EntRoomType
     */
    cOSTDATA?: number;
    /**
     * ROOMTYPEDATA holds the value of the "ROOMTYPEDATA" field.
     * @type {string}
     * @memberof EntRoomType
     */
    rOOMTYPEDATA?: string;
    /**
     * 
     * @type {EntRoomTypeEdges}
     * @memberof EntRoomType
     */
    edges?: EntRoomTypeEdges;
    /**
     * ID of the ent.
     * @type {number}
     * @memberof EntRoomType
     */
    id?: number;
}

export function EntRoomTypeFromJSON(json: any): EntRoomType {
    return EntRoomTypeFromJSONTyped(json, false);
}

export function EntRoomTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomType {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cOSTDATA': !exists(json, 'COSTDATA') ? undefined : json['COSTDATA'],
        'rOOMTYPEDATA': !exists(json, 'ROOMTYPEDATA') ? undefined : json['ROOMTYPEDATA'],
        'edges': !exists(json, 'edges') ? undefined : EntRoomTypeEdgesFromJSON(json['edges']),
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function EntRoomTypeToJSON(value?: EntRoomType | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'COSTDATA': value.cOSTDATA,
        'ROOMTYPEDATA': value.rOOMTYPEDATA,
        'edges': EntRoomTypeEdgesToJSON(value.edges),
        'id': value.id,
    };
}


