/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    EntBook,
    EntBookFromJSON,
    EntBookFromJSONTyped,
    EntBookToJSON,
    EntRoomInfo,
    EntRoomInfoFromJSON,
    EntRoomInfoFromJSONTyped,
    EntRoomInfoToJSON,
    EntRoomStatus,
    EntRoomStatusFromJSON,
    EntRoomStatusFromJSONTyped,
    EntRoomStatusToJSON,
    EntRoomType,
    EntRoomTypeFromJSON,
    EntRoomTypeFromJSONTyped,
    EntRoomTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface EntRoomEdges
 */
export interface EntRoomEdges {
    /**
     * ROOMBOOK holds the value of the ROOM_BOOK edge.
     * @type {Array<EntBook>}
     * @memberof EntRoomEdges
     */
    roombook?: Array<EntBook>;
    /**
     * 
     * @type {EntRoomInfo}
     * @memberof EntRoomEdges
     */
    roominfo?: EntRoomInfo;
    /**
     * 
     * @type {EntRoomType}
     * @memberof EntRoomEdges
     */
    roomroomtype?: EntRoomType;
    /**
     * 
     * @type {EntRoomStatus}
     * @memberof EntRoomEdges
     */
    roomstatus?: EntRoomStatus;
}

export function EntRoomEdgesFromJSON(json: any): EntRoomEdges {
    return EntRoomEdgesFromJSONTyped(json, false);
}

export function EntRoomEdgesFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntRoomEdges {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'roombook': !exists(json, 'ROOMBOOK') ? undefined : ((json['ROOMBOOK'] as Array<any>).map(EntBookFromJSON)),
        'roominfo': !exists(json, 'ROOMINFO') ? undefined : EntRoomInfoFromJSON(json['ROOMINFO']),
        'roomroomtype': !exists(json, 'ROOMROOMTYPE') ? undefined : EntRoomTypeFromJSON(json['ROOMROOMTYPE']),
        'roomstatus': !exists(json, 'ROOMSTATUS') ? undefined : EntRoomStatusFromJSON(json['ROOMSTATUS']),
    };
}

export function EntRoomEdgesToJSON(value?: EntRoomEdges | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'roombook': value.roombook === undefined ? undefined : ((value.roombook as Array<any>).map(EntBookToJSON)),
        'roominfo': EntRoomInfoToJSON(value.roominfo),
        'roomroomtype': EntRoomTypeToJSON(value.roomroomtype),
        'roomstatus': EntRoomStatusToJSON(value.roomstatus),
    };
}


