// Code generated by entc, DO NOT EDIT.

package room

const (
	// Label holds the string label denoting the room type in the database.
	Label = "room"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldROOMNAME holds the string denoting the roomname field in the database.
	FieldROOMNAME = "roomname"

	// EdgeROOMBOOK holds the string denoting the room_book edge name in mutations.
	EdgeROOMBOOK = "ROOM_BOOK"
	// EdgeROOMROOMTYPE holds the string denoting the room_roomtype edge name in mutations.
	EdgeROOMROOMTYPE = "ROOM_ROOMTYPE"
	// EdgeROOMSTATUS holds the string denoting the room_status edge name in mutations.
	EdgeROOMSTATUS = "ROOM_STATUS"
	// EdgeROOMINFO holds the string denoting the room_info edge name in mutations.
	EdgeROOMINFO = "ROOM_INFO"

	// Table holds the table name of the room in the database.
	Table = "rooms"
	// ROOMBOOKTable is the table the holds the ROOM_BOOK relation/edge.
	ROOMBOOKTable = "books"
	// ROOMBOOKInverseTable is the table name for the Book entity.
	// It exists in this package in order to avoid circular dependency with the "book" package.
	ROOMBOOKInverseTable = "books"
	// ROOMBOOKColumn is the table column denoting the ROOM_BOOK relation/edge.
	ROOMBOOKColumn = "room_room_book"
	// ROOMROOMTYPETable is the table the holds the ROOM_ROOMTYPE relation/edge.
	ROOMROOMTYPETable = "rooms"
	// ROOMROOMTYPEInverseTable is the table name for the RoomType entity.
	// It exists in this package in order to avoid circular dependency with the "roomtype" package.
	ROOMROOMTYPEInverseTable = "room_types"
	// ROOMROOMTYPEColumn is the table column denoting the ROOM_ROOMTYPE relation/edge.
	ROOMROOMTYPEColumn = "room_type_roomtype_room"
	// ROOMSTATUSTable is the table the holds the ROOM_STATUS relation/edge.
	ROOMSTATUSTable = "rooms"
	// ROOMSTATUSInverseTable is the table name for the RoomStatus entity.
	// It exists in this package in order to avoid circular dependency with the "roomstatus" package.
	ROOMSTATUSInverseTable = "room_status"
	// ROOMSTATUSColumn is the table column denoting the ROOM_STATUS relation/edge.
	ROOMSTATUSColumn = "room_status_status_room"
	// ROOMINFOTable is the table the holds the ROOM_INFO relation/edge.
	ROOMINFOTable = "rooms"
	// ROOMINFOInverseTable is the table name for the RoomInfo entity.
	// It exists in this package in order to avoid circular dependency with the "roominfo" package.
	ROOMINFOInverseTable = "room_infos"
	// ROOMINFOColumn is the table column denoting the ROOM_INFO relation/edge.
	ROOMINFOColumn = "room_info_info_room"
)

// Columns holds all SQL columns for room fields.
var Columns = []string{
	FieldID,
	FieldROOMNAME,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Room type.
var ForeignKeys = []string{
	"room_info_info_room",
	"room_status_status_room",
	"room_type_roomtype_room",
}

var (
	// ROOMNAMEValidator is a validator for the "ROOMNAME" field. It is called by the builders before save.
	ROOMNAMEValidator func(string) error
)
