// Code generated by entc, DO NOT EDIT.

package roomstatus

const (
	// Label holds the string label denoting the roomstatus type in the database.
	Label = "room_status"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSTATUSDATA holds the string denoting the statusdata field in the database.
	FieldSTATUSDATA = "statusdata"

	// EdgeSTATUSROOM holds the string denoting the status_room edge name in mutations.
	EdgeSTATUSROOM = "STATUS_ROOM"

	// Table holds the table name of the roomstatus in the database.
	Table = "room_status"
	// STATUSROOMTable is the table the holds the STATUS_ROOM relation/edge.
	STATUSROOMTable = "rooms"
	// STATUSROOMInverseTable is the table name for the Room entity.
	// It exists in this package in order to avoid circular dependency with the "room" package.
	STATUSROOMInverseTable = "rooms"
	// STATUSROOMColumn is the table column denoting the STATUS_ROOM relation/edge.
	STATUSROOMColumn = "room_status_status_room"
)

// Columns holds all SQL columns for roomstatus fields.
var Columns = []string{
	FieldID,
	FieldSTATUSDATA,
}

var (
	// STATUSDATAValidator is a validator for the "STATUSDATA" field. It is called by the builders before save.
	STATUSDATAValidator func(string) error
)
