// Code generated by entc, DO NOT EDIT.

package roomstatus

import (
	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/m16_z/app/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id int) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// STATUSDATA applies equality check predicate on the "STATUSDATA" field. It's identical to STATUSDATAEQ.
func STATUSDATA(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATAEQ applies the EQ predicate on the "STATUSDATA" field.
func STATUSDATAEQ(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATANEQ applies the NEQ predicate on the "STATUSDATA" field.
func STATUSDATANEQ(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATAIn applies the In predicate on the "STATUSDATA" field.
func STATUSDATAIn(vs ...string) predicate.RoomStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RoomStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldSTATUSDATA), v...))
	})
}

// STATUSDATANotIn applies the NotIn predicate on the "STATUSDATA" field.
func STATUSDATANotIn(vs ...string) predicate.RoomStatus {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.RoomStatus(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldSTATUSDATA), v...))
	})
}

// STATUSDATAGT applies the GT predicate on the "STATUSDATA" field.
func STATUSDATAGT(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATAGTE applies the GTE predicate on the "STATUSDATA" field.
func STATUSDATAGTE(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATALT applies the LT predicate on the "STATUSDATA" field.
func STATUSDATALT(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATALTE applies the LTE predicate on the "STATUSDATA" field.
func STATUSDATALTE(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATAContains applies the Contains predicate on the "STATUSDATA" field.
func STATUSDATAContains(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATAHasPrefix applies the HasPrefix predicate on the "STATUSDATA" field.
func STATUSDATAHasPrefix(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATAHasSuffix applies the HasSuffix predicate on the "STATUSDATA" field.
func STATUSDATAHasSuffix(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATAEqualFold applies the EqualFold predicate on the "STATUSDATA" field.
func STATUSDATAEqualFold(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldSTATUSDATA), v))
	})
}

// STATUSDATAContainsFold applies the ContainsFold predicate on the "STATUSDATA" field.
func STATUSDATAContainsFold(v string) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldSTATUSDATA), v))
	})
}

// HasSTATUSROOM applies the HasEdge predicate on the "STATUS_ROOM" edge.
func HasSTATUSROOM() predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(STATUSROOMTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, STATUSROOMTable, STATUSROOMColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSTATUSROOMWith applies the HasEdge predicate on the "STATUS_ROOM" edge with a given conditions (other predicates).
func HasSTATUSROOMWith(preds ...predicate.Room) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(STATUSROOMInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, STATUSROOMTable, STATUSROOMColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.RoomStatus) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.RoomStatus) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoomStatus) predicate.RoomStatus {
	return predicate.RoomStatus(func(s *sql.Selector) {
		p(s.Not())
	})
}
